name: jiant_glt
channels:
    - pytorch
dependencies:
    - python=3.6.12
    - pytorch==1.5.1
    - torchvision=0.6.1
    - numpy=1.14.5
    - nltk=3.2.5
    - scikit-learn=0.19.1
    - pandas=0.23.0
    - pytz=2017.3
    - pip:
        - allennlp==0.9.0
        - ipdb
        - tensorboard
        - tensorboardX==1.2
        - sendgrid==5.4.1
        - transformers==2.11.0
